---
title: "**Segundo Semestre**"
--- 

<br>
<br>


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

<br>

<div class=text-justify>

# **Programación** 

<br>

- [Presentación](materiales/segundo_semestre/programacion/Presentation.pdf){target="_blank"}

- [Primera clase](materiales/segundo_semestre/programacion/python1.pdf){target="_blank"}

- [Segunda clase](materiales/segundo_semestre/programacion/python2.pdf){target="_blank"}

- [Tercera clase](materiales/segundo_semestre/programacion/ip_python3.pdf){target="_blank"}

- [Geopandas](materiales/segundo_semestre/programacion/PresentationGeoPandas.pdf){target="_blank"}

- [Guia rápida matlab, python y R](materiales/segundo_semestre/programacion/PythonMatlabAndR.pdf){target="_blank"}

- [Ejercicios 1](materiales/segundo_semestre/programacion/EjerciciosPython.pdf){target="_blank"}

- [Ejercicios 2](materiales/segundo_semestre/programacion/EjerciciosClase3.pdf){target="_blank"}

<br>

<br>


# **Modelos Estadísticos I** 
<br>

- [Notas y materiales de la clase](materiales/segundo_semestre/modelos_estadisticos_1/notas.zip){target="_blank"}

- [Primer parcial](materiales/segundo_semestre/modelos_estadisticos_1/primer_parcial.zip){target="_blank"}

- [Segundo parcial](materiales/segundo_semestre/modelos_estadisticos_1/segundo_parcial.zip){target="_blank"}

- [Tareas](materiales/segundo_semestre/modelos_estadisticos_1/tareas.zip){target="_blank"}

