---
title: "**Primer Semestre**"
--- 

<br>
<br>


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

<div class=text-justify>

# **Álgebra Matricial y Optimización** 

<br>

- [Presentación clases 10, 11, 24 y 25 enero. Desde espacios vectoriales hasta factorización LU](materiales/primer_sem/algebra_matricial/Álgebra Matricial Segunda Parte.pdf){target="_blank"}

- [Notas pizarra 10-01-2020](materiales/primer_sem/algebra_matricial/AlgebraMNotas10012020.pdf){target="_blank"}

- [Notas pizarra 11-01-2020](materiales/primer_sem/algebra_matricial/AlgebraMNotas11012020.pdf){target="_blank"}

- [Solución Tarea 1](materiales/primer_sem/algebra_matricial/Tarea1_solucion.pdf){target="_blank"}

<br>

- [Notas pizarra 24-01-2020](materiales/primer_sem/algebra_matricial/Nota_Algebra24012020.pdf){target="_blank"}

- [Notas pizarra 25-01-2020](materiales/primer_sem/algebra_matricial/Nota_Algebra25012020.pdf){target="_blank"}

- [Tarea 2](materiales/primer_sem/algebra_matricial/Tarea-2.pdf){target="_blank"}


<br>

- [Presentación clases 07 y 08 febrero. Retoma desde lámina 83, con ejemplos de descomposición LU, espacios asociados y valores propios](materiales/primer_sem/algebra_matricial/2020 inegi algebra matricial.pdf){target="_blank"}

- [Notas pizarra 07-02-2020](materiales/primer_sem/algebra_matricial/NOTA_ALGEBRA_S5_07022020.pdf){target="_blank"}

- [Notas pizarra 08-02-2020](materiales/primer_sem/algebra_matricial/NOTA_ALGEBRA_S6_08022020.pdf){target="_blank"}


<br>

- [Presentación Parte Final](materiales/primer_sem/algebra_matricial/Álgebra Matricial _ Parte Final.pdf){target="_blank"}

- [Presentación Asesorías](materiales/primer_sem/algebra_matricial/PRESENTACION ASESORIA.pdf){target="_blank"}

- [Notas pizarra 21-02-2020](materiales/primer_sem/algebra_matricial/NOTA_ALGEBRA_S7_21022020.pdf){target="_blank"}

- [Notas pizarra 22-02-2020](materiales/primer_sem/algebra_matricial/NOTA_ALGEBRA_S8_22022020.pdf){target="_blank"}

- [Tarea 4](materiales/primer_sem/algebra_matricial/Tarea-4.pdf){target="_blank"}



<br>
<br>
<br>

# **Inferencia Estadística** 

<br>

- [Temario](materiales/primer_sem/inferencia_estadistica/Temario.pdf){target="_blank"}

<br>


- [Presentación 17 y 18 de enero. Variables aleatorias y distribuciones de probabilidad](materiales/primer_sem/inferencia_estadistica/Inf_Estadistica_1.pdf){target="_blank"}

- [Notas pizarra 17-01-2020](materiales/primer_sem/inferencia_estadistica/17012020_INFERENCIA_ESTADISTICA_NOTA.pdf){target="_blank"}

- [Notas pizarra 18-01-2020](materiales/primer_sem/inferencia_estadistica/18012020_INFERENCIA_ESTADISTICA_NOTA.pdf){target="_blank"}

- [Tarea 1](materiales/primer_sem/inferencia_estadistica/Tarea1.pdf){target="_blank"}

- [Solución Tarea 1](materiales/primer_sem/inferencia_estadistica/T01_Solution.pdf){target="_blank"}

<br>

<br>


- [Presentación 31 de enero y 01 de febrero. Variables aleatorias y distribuciones de probabilidad multivariadas](materiales/primer_sem/inferencia_estadistica/Inf_Estadistica_2.pdf){target="_blank"}

- [Notas pizarra 31-01-2020](materiales/primer_sem/inferencia_estadistica/31012020_INFERENCIA_ESTADISTICA_NOTA.pdf){target="_blank"}

- [Notas pizarra 01-02-2020](materiales/primer_sem/inferencia_estadistica/01022020_INFERENCIA_ESTADISTICA_NOTA.pdf){target="_blank"}

- [Tarea 2](materiales/primer_sem/inferencia_estadistica/Tarea2.pdf){target="_blank"}

- [Solución Tarea 2](materiales/primer_sem/inferencia_estadistica/Tarea2_sol.pdf){target="_blank"}


<br>

<br>

- [Presentación 14 y 15 de febrero.  Distribuciones muestrales y métodos de estimación](materiales/primer_sem/inferencia_estadistica/Inf_Estadistica_3.pdf){target="_blank"}

- [Notas pizarra 14-02-2020 parte 1](materiales/primer_sem/inferencia_estadistica/NOTA_INFERENCIA_S5_A_14022020.pdf){target="_blank"}

- [Notas pizarra 14-02-2020 parte 2](materiales/primer_sem/inferencia_estadistica/NOTA_INFERENCIA_S5_B_14022020.pdf){target="_blank"}

- [Notas pizarra 15-02-2020](materiales/primer_sem/inferencia_estadistica/NOTA_INFERENCIA_S6_15022020.pdf){target="_blank"}

- [Tarea 3](materiales/primer_sem/inferencia_estadistica/Tarea3.pdf){target="_blank"}



<br>

<br>


- [Notas pizarra 28-02-2020](materiales/primer_sem/inferencia_estadistica/NOTA_INFERENCIA_S7_28022020.pdf){target="_blank"}

- [Notas pizarra 29-02-2020](materiales/primer_sem/inferencia_estadistica/NOTA_INFERENCIA_S8_29022020.pdf){target="_blank"}

- [Tarea 4](materiales/primer_sem/inferencia_estadistica/Tarea4.pdf){target="_blank"}






