---
title: "**Recursos**"
--- 

<br>
<br>


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

<div class=text-justify>

# **Tutorial "Curso básico de R"** 

- [Tutorial](curso_r/tutorial_pdf/Curso_basico_de_R.pdf){target="_blank"}

- [Carpeta de materiales del tutorial](curso_r/tutorial_pdf/materiales_tutorial_R.zip){target="_blank"}

<br>


# **Curso R / RMarkdown**

- [Tutorial Documentos en RMarkdown](curso_r/r_rmarkdown/curso_r_rmarkdown.html){target="_blank"}

<br>


# **MiniCurso de R**

- [Minicurso](curso_r/MiniCursoR_2.pdf){target="_blank"}

<br>

# **Libros**

- [Anton,H. *Álgebra lineal*](libros_pdf/algebra_lineal_Anton.pdf){target="_blank"}

- [Friedberg & Insel. *Álgebra lineal*](libros_pdf/algebra_lineal_Friedberg_Insel.pdf){target="_blank"}

- [García. *Álgebra lineal, problemas resueltos*](libros_pdf/algebra_lineal_problemas_resueltos_Garcia.pdf){target="_blank"}

- [Goloviná. *Álgebra lineal y aplicaciones*](libros_pdf/algebra_lineal_aplicaciones_Golovina.pdf){target="_blank"}

- [Acuña. *Análisis de Regresión*](libros_pdf/analisis_de_regresion_Acuña.pdf){target="_blank"}

- [Muñoz & Sánchez. *Apuntes de Estadística*](libros_pdf/apuntes_de_estadistica_Muñoz_Sánchez.pdf){target="_blank"}

- [Leithold. *Cálculo*](libros_pdf/cálculo_Leithold.pdf){target="_blank"}

- [Marsden & Tromba. *Cálculo Vectorial*](libros_pdf/cálculo_vectorial_Marsden_Tromba.pdf){target="_blank"}

- [Courant & John. *Cálculo y Análisis Matemático*](libros_pdf/cálculo_analisis_matemático_Courant_John.zip){target="_blank"}

- [Apostol. *Calculus*](libros_pdf/calculus_Apostol.zip){target="_blank"}

- [Agresti. *Categorical Data Analysis*](libros_pdf/cda_Agresti.pdf){target="_blank"}

- [Solow. *Como Hacer y Entender Demostraciones en Matemáticas*](libros_pdf/demostraciones_Solow.pdf){target="_blank"}

- [Triola. *Estadística*](libros_pdf/estadística_Triola.pdf){target="_blank"}
 
- [Ross. *Introduction To Probability Models*](libros_pdf/prob_models_Ross.pdf){target="_blank"}
  
- [Aleksandrov & Kolmogorov. *Matemática*](libros_pdf/matemática_Aleksandrov_Kolmogorov.zip){target="_blank"}
 
- [Rosell. *Matemáticas Aplicadas a las Ciencias Sociales*](libros_pdf/macs_Rosell.pdf){target="_blank"} 

- [Canavos. *Probabilidad y Estadística*](libros_pdf/probabilidad_estadística_Canavos.pdf){target="_blank"} 

- [Rice. *Mathematical Statistics and Data Analysis*](libros_pdf/Rice_J._Mathematical_Statistics_and_Data_Analysis.pdf){target="_blank"} 

- [Meyer. *Probabilidad y Aplicaciones Estadisticas*](libros_pdf/Meyer Probabilidad y Aplicaciones Estadisticas Edicion Revisada.pdf){target="_blank"}

- [Lay. *Linear Algebra and Its Applications*](libros_pdf/Lay_Linear_algebra.pdf){target="_blank"}

- [Fieller. *Basics of Matrix Algebra for Statistics with R*](libros_pdf/Fieller 16 Basics of Matrix Algebra for Statistics with R.pdf){target="_blank"}

- [Sánchez Corona. *Probabilidad y Estadística*](libros_pdf/Cap8_9_Sanchez Corona - Probabilidad y estadística(2004).pdf){target="_blank"}

- [Wasserman. *All of Statistics: A Concise Course in Statistical Inference*](libros_pdf/Wasserman_All_of_statistics.pdf){target="_blank"}

- [Dalgaard. *Introductory Statistics with R*](libros_pdf/Introductory_Statistics_with_R__2nd_ed.pdf){target="_blank"}

- [Baclawski *Introduction to Probability with R*](libros_pdf/Baclawski, Kenneth - Introduction to Probability with R-CRC Press (2008).pdf){target="_blank"}

- [Dekking *A Modern Introduction to Probability and Statistics*](libros_pdf/Modern_intro_probability_statistics_Dekking05.pdf){target="_blank"}

- [Dobrow *Probability With Applications and R*](libros_pdf/Robert P. Dobrow - Probability_ With Applications and R-Wiley (2013).pdf){target="_blank"}

- [Jones & Maillardet *Introduction to Scientific Programming and Simulation using R*](libros_pdf/introduction-scientific-programming-simulation-r-2nd (002).pdf){target="_blank"}


- [Chernick & LaBudde *An Introduction to Bootstrap Methods with Applications to R*](libros_pdf/Bootstrap_Chernick2011.pdf){target="_blank"}

- [Zuur, N.leno & Meesters *A Beginner's Guide to R.*](libros_pdf/epdf.tips_a-beginners-guide-to-r-use-r.pdf){target="_blank"}

- [Albert & Rizzo *R by example*](libros_pdf/epdf.tips_r-by-example-use-r.pdf){target="_blank"}

- [Cohen & Cohen *Statistics and Data with R*](libros_pdf/epdf.tips_statistics-and-data-with-r-an-applied-approach-thr.pdf){target="_blank"}

- [*Learning Python*](libros_pdf/Learning Python 5th Ed 2013.pdf){target="_blank"}

- [*Numerical Methods in Engineering with Python 3*](libros_pdf/Numerical Methods in Engineering with Python 3.pdf){target="_blank"}

- [Novales. *Análisis de regresión*](libros_pdf/Analisis de Regresion.pdf){target="_blank"}){target="_blank"}

- [Nicholas J. Horton, Ken Kleinman. *Using R and RStudio for Data Management, Statistical Analysis and Graphics*](libros_pdf/Using R and RStudio for Data Management, Statistical Analysis and Graphics by Nicholas J. Horton, Ken Kleinman (z-lib.org).pdf){target="_blank"}){target="_blank"}



</div>