---
title: "**Presentación**"
--- 

<br>
<br>


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

<div class=text-justify>

# **Objetivo** 

Página web para compartir información sobre la Maestría en Análisis Estadístico y Computación del CIMAT.

Cualquier aportación, comentarios e información al respecto, favor de dirigirlas al correo: raul.mejia@inegi.org.mx

<br>

Correos CIMAT:

- posgrado.maec@cimat.mx  (para asesorías y tareas)

- maec@inegi.org.mx (trámites y asuntos administrativos)

<br>

# **Plataformas**

[Enlace aula virtual](https://bluejeans.com/353107177){target='_blank'}

<br>

- [Plataforma de los cursos CIMAT](http://201.116.172.104:8080/){target="_blank"}

- [Calendario 2020](materiales/Calendario MAEC 2020.pdf){target="_blank"}



<br>
<br>

# **Propedéutico**

<br>

## **Cálculo**

- [Presentación de la clase](materiales/prope/PropedeuticoCalculo.pdf){target="_blank"}

- [Tarea](materiales/prope/TareaCalculo.pdf){target="_blank"}

<br>

## **Álgebra Matricial**

- [Presentación de la clase](materiales/prope/prope_inegi.pdf){target="_blank"}

- [Tarea](materiales/prope/tarea_prope_inegi.pdf){target="_blank"}

<br>

## **Introducción a la Programación (R)**

- [Presentación de la clase](materiales/prope/programacion_r/Introduccion-programacion-R.pdf){target="_blank"}

- [Descargar carpeta](materiales/prope/programacion_r/programacion_r.zip)

- [Tarea](materiales/prope/Tarea-programacion-R.pdf)



<br>

## **Probabilidad**

- [Presentación de la clase. Parte 1](materiales/prope/MAEC_Clase1_Prob.pdf){target="_blank"}

- [Presentación de la clase. Parte 2](materiales/prope/MAEC_Clase2_Prob.pdf){target="_blank"}

- [Tarea](materiales/prope/MAEC_Tarea1_Probabilidad.pdf)



</div>




